name: Question
description: I'm having trouble using these actions
title: "How do I...? "
labels: ["question"]
body:
  - type: markdown
    attributes:
      value: |
        enable debugging

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true

  - type: textarea
    id: workflow
    attributes:
      label: Workflow YAML
      description: Please copy and paste the relevant workflow yaml. This will be automatically formatted, so no need for backticks.
      render: yaml

  - type: input
    id: backend
    attributes:
      label: Backend
      description: What terraform backend are you using?
      placeholder: s3

  - type: textarea
    id: workflow-logs
    attributes:
      label: Workflow log
      description: Please copy and paste the relevant workflow log output. This will be automatically formatted, so no need for backticks.
      render: shell

